"""The voice gate must not mistake NOVA's own voice for the user's.

These tests run against *real* audio, not synthetic tones: a recorded Gemini
Live response stands in for what comes out of the speakers, and recorded
speech stands in for the user. That matters, because the bug they exist to
prevent was invisible to any test using a fixed-amplitude signal — it only
appears once the echo is as loud and as bursty as real speech.

The echo path is modelled with several taps and a little clipping rather than
a single clean delay. A one-tap room would flatter the canceller, which is
also one tap, and the test would then prove nothing about a real desk.

Fixtures are generated by tools/make_voice_fixtures.py and cached under
tests/fixtures/voice/. If they are missing the tests skip rather than fail, so
a checkout without them is still green.
"""
from __future__ import annotations

import sys
import unittest
import wave
from pathlib import Path

import numpy as np

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from nova_voice import EchoCanceller, VoiceGate, frame_rms

FIXTURES = Path(__file__).resolve().parent / "fixtures" / "voice"
NOVA_WAV = FIXTURES / "nova_speech_24k.wav"
USER_WAV = FIXTURES / "user_speech_16k.wav"

FRAME = 1024              # samples @ 16 kHz == 64 ms, NOVA's mic block size
FRAME_MS = FRAME / 16.0


def _read(path: Path) -> tuple[np.ndarray, int]:
    with wave.open(str(path), "rb") as w:
        return (np.frombuffer(w.readframes(w.getnframes()), dtype=np.int16),
                w.getframerate())


def _to_16k(a: np.ndarray, rate: int) -> np.ndarray:
    if rate == 16000:
        return a
    idx = (np.arange(int(len(a) * 16000 / rate)) * rate / 16000).astype(np.int64)
    return a[idx[idx < len(a)]]


class Room:
    """A speaker-to-microphone path with delay, reverberation and clipping."""

    #: (delay in samples, gain relative to the direct path)
    TAPS = ((0, 1.0), (411, 0.45), (983, 0.22), (1877, 0.11))

    def __init__(self, coupling: float, base_delay_s: float = 0.19):
        self.coupling = coupling
        self.base = int(16000 * base_delay_s)

    def echo_of(self, played: np.ndarray, upto: int, n: int) -> np.ndarray:
        """The echo arriving in the sample window ending at ``upto``."""
        out = np.zeros(n, dtype=np.float64)
        for delay, gain in self.TAPS:
            start = upto - self.base - delay
            if start < 0:
                continue
            seg = played[start:start + n]
            if seg.size:
                out[:seg.size] += seg.astype(np.float64) * gain
        return np.clip(out * self.coupling, -32768, 32767)


@unittest.skipUnless(NOVA_WAV.exists() and USER_WAV.exists(),
                     "voice fixtures not generated; run tools/make_voice_fixtures.py")
class EchoRejectionTests(unittest.TestCase):
    """NOVA speaking into her own microphone must never trigger barge-in."""

    @classmethod
    def setUpClass(cls):
        nova, rate = _read(NOVA_WAV)
        cls.nova24, cls.nova_rate = nova, rate
        cls.nova16 = _to_16k(nova, rate)
        cls.user, _ = _read(USER_WAV)

    def _run(self, gate, coupling, user=None, user_at=None,
             noise_rms=40.0, seed=1234):
        """Play NOVA's audio into a room and back into the gate's microphone.

        Returns the frame index of the first barge-in, or None.
        """
        rng = np.random.default_rng(seed)
        room = Room(coupling)
        fired: list[int] = []
        gate._on_barge_in = lambda: fired.append(1)
        gate.set_speaking(True)

        user_start = None if user_at is None else int(user_at * 16000 / FRAME)
        n_frames = len(self.nova16) // FRAME

        for i in range(n_frames):
            # The playback thread hands the speaker a chunk, and tells the gate.
            lo24 = i * FRAME * self.nova_rate // 16000
            hi24 = (i + 1) * FRAME * self.nova_rate // 16000
            seg24 = self.nova24[lo24:hi24]
            if seg24.size:
                gate.reference(seg24.tobytes(), self.nova_rate)

            mic = rng.normal(0, noise_rms, FRAME)
            mic += room.echo_of(self.nova16, (i + 1) * FRAME, FRAME)
            if user_start is not None and i >= user_start:
                k = (i - user_start) * FRAME
                seg = self.user[k:k + FRAME]
                if seg.size == FRAME:
                    mic += seg.astype(np.float64)

            gate.process(np.clip(mic, -32768, 32767).astype(np.int16))
            if fired:
                return i
        return None

    # ── the regression ────────────────────────────────────────────────────

    def test_nova_never_interrupts_herself(self):
        """The bug that broke NOVA's voice: her own greeting cut itself off.

        Swept from a quiet external speaker to a loud laptop one. None of it
        may register as the user talking.
        """
        for coupling in (0.05, 0.10, 0.15, 0.25, 0.40, 0.60):
            with self.subTest(coupling=coupling):
                gate = VoiceGate(chunk_samples=FRAME, simple=False)
                at = self._run(gate, coupling)
                self.assertIsNone(
                    at, f"NOVA interrupted herself {(at or 0) * FRAME_MS:.0f} ms "
                        f"in at {coupling:.0%} coupling; gate={gate.snapshot()}")

    def test_fixture_reproduces_the_original_bug(self):
        """Proves the material is actually capable of triggering the failure.

        A green test on audio too quiet to trip anything would be worthless.
        This replays the *previous* policy directly — plain frame RMS over a
        fixed 350, two consecutive frames, no echo cancellation anywhere — and
        asserts it does fire on this same recording, within the first seconds,
        exactly as the production logs recorded it doing.
        """
        rng = np.random.default_rng(1234)
        room = Room(0.15)
        runs = 0
        for i in range(len(self.nova16) // FRAME):
            mic = rng.normal(0, 40, FRAME)
            mic += room.echo_of(self.nova16, (i + 1) * FRAME, FRAME)
            frame = np.clip(mic, -32768, 32767).astype(np.int16)
            runs = runs + 1 if frame_rms(frame) > 350.0 else 0
            if runs >= 2:
                self.assertLess(i * FRAME_MS, 3000,
                                "original bug appeared within the first seconds")
                return
        self.fail("fixture cannot reproduce the original bug")

    # ── barge-in must still work ──────────────────────────────────────────

    def test_real_speech_interrupts(self):
        for coupling in (0.10, 0.15, 0.25, 0.40):
            with self.subTest(coupling=coupling):
                gate = VoiceGate(chunk_samples=FRAME, simple=False)
                at = self._run(gate, coupling, user=self.user, user_at=1.0)
                self.assertIsNotNone(
                    at, f"real speech did not interrupt at {coupling:.0%} "
                        f"coupling; gate={gate.snapshot()}")
                self.assertGreaterEqual(at * FRAME_MS, 1000,
                                        "fired before the user said anything")
                self.assertLess(at * FRAME_MS - 1000, 1200,
                                "took over a second to notice the user")

    def test_barge_in_reopens_the_microphone_immediately(self):
        """No cooldown after an interruption, or the user's words are eaten."""
        gate = VoiceGate(chunk_samples=FRAME, simple=False)
        at = self._run(gate, 0.15, user=self.user, user_at=1.0)
        self.assertIsNotNone(at)
        self.assertFalse(gate.speaking)
        loud = (np.random.default_rng(0).normal(0, 4000, FRAME)).astype(np.int16)
        self.assertEqual(gate.process(loud), loud.tobytes(),
                         "gate was still muting straight after a barge-in")

    # ── invariants ────────────────────────────────────────────────────────

    def test_silence_is_transmitted_never_withheld(self):
        """A gap in the stream is worse than silence: never return None."""
        gate = VoiceGate(chunk_samples=FRAME, simple=False)
        gate.set_speaking(True)
        out = gate.process(np.zeros(FRAME, dtype=np.int16))
        self.assertEqual(out, bytes(FRAME * 2))

    def test_listening_frames_pass_through_unchanged(self):
        gate = VoiceGate(chunk_samples=FRAME, simple=False)
        frame = (np.random.default_rng(0).normal(0, 3000, FRAME)).astype(np.int16)
        self.assertEqual(gate.process(frame), frame.tobytes())

    def test_transmitted_audio_is_never_the_cancelled_signal(self):
        """The AEC informs the decision only; the model hears the real mic."""
        gate = VoiceGate(chunk_samples=FRAME, simple=False)
        gate.reference(self.nova24[:4096].tobytes(), self.nova_rate)
        frame = (np.random.default_rng(0).normal(0, 3000, FRAME)).astype(np.int16)
        self.assertEqual(gate.process(frame), frame.tobytes())


@unittest.skipUnless(NOVA_WAV.exists(), "voice fixtures not generated")
class EchoCancellerTests(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        nova, rate = _read(NOVA_WAV)
        cls.nova24, cls.rate = nova, rate
        cls.nova16 = _to_16k(nova, rate)

    def test_cancels_echo_measurably(self):
        """Cancellation is the mechanism, so measure it, don't assume it.

        Five decibels, not fifteen. One tap cannot model a reverberant room,
        and the honest measurement here is about 6 dB. The gate does not rely
        on raw cancellation being large — it relies on what is *left over*
        being proportional to playback level and much smaller than a person
        talking, which :meth:`test_leakage_separates_echo_from_speech` pins
        down and the end-to-end gate tests enforce. This test exists to catch
        the canceller silently doing nothing at all, which is what a wrong lag
        or a frozen gain looks like.
        """
        ec = EchoCanceller(frame=FRAME)
        room = Room(0.15)
        rng = np.random.default_rng(7)
        mic_peak = res_peak = 0.0
        for i in range(len(self.nova16) // FRAME):
            lo = i * FRAME * self.rate // 16000
            hi = (i + 1) * FRAME * self.rate // 16000
            ec.reference(self.nova24[lo:hi].tobytes(), self.rate)
            mic = rng.normal(0, 40, FRAME)
            mic += room.echo_of(self.nova16, (i + 1) * FRAME, FRAME)
            frame = np.clip(mic, -32768, 32767).astype(np.int16)
            mic_peak = max(mic_peak, frame_rms(frame))
            res_peak = max(res_peak, ec.residual_rms(frame))
        db = 20 * np.log10(mic_peak / max(res_peak, 1e-9))
        self.assertGreater(db, 5.0,
                           f"only {db:.1f} dB of cancellation "
                           f"(mic {mic_peak:.0f} -> residual {res_peak:.0f})")

    def test_leakage_separates_echo_from_speech(self):
        """The property the whole detector rests on, asserted directly.

        Leakage is the post-cancellation residual as a fraction of the
        playback level driving it, both averaged over the same short window
        the detector uses. NOVA's own voice must sit far below a person's, at
        every coupling, or no threshold can tell them apart. Measured
        per-frame instead of smoothed it does not: uncancelled reverberation
        spikes to a ratio of 0.52 whenever the reference dips between words,
        which is why the gate smooths before it decides.
        """
        user, _ = _read(USER_WAV)
        for coupling in (0.10, 0.25, 0.40):
            with self.subTest(coupling=coupling):
                echo_only = self._leak_series(coupling, None)
                double = self._leak_series(coupling, user)
                quiet = float(np.percentile(echo_only, 90))
                loud = float(np.percentile(double, 75))
                # Absolute leakage necessarily rises with coupling — measured
                # 0.10, 0.23, 0.35 across this sweep. The property the
                # detector actually rests on is the *gap*, so that is what is
                # asserted tightly; the absolute bound only catches
                # cancellation failing outright.
                self.assertLess(quiet, 0.45,
                                f"echo leaks {quiet:.2f} of playback level")
                self.assertGreater(loud, quiet * 2.0,
                                   f"speech ({loud:.2f}) is not clear of echo "
                                   f"({quiet:.2f}) at {coupling:.0%} coupling")

    def _leak_series(self, coupling, user):
        from nova_voice import RESIDUAL_SMOOTHING_FRAMES as W
        ec = EchoCanceller(frame=FRAME)
        room = Room(coupling)
        rng = np.random.default_rng(7)
        out, res_hist, ref_hist = [], [], []
        for i in range(len(self.nova16) // FRAME):
            lo = i * FRAME * self.rate // 16000
            hi = (i + 1) * FRAME * self.rate // 16000
            ec.reference(self.nova24[lo:hi].tobytes(), self.rate)
            mic = rng.normal(0, 40, FRAME)
            mic += room.echo_of(self.nova16, (i + 1) * FRAME, FRAME)
            speaking = False
            if user is not None and i >= 15:
                k = (i - 15) * FRAME
                seg = user[k:k + FRAME]
                if seg.size == FRAME:
                    mic += seg.astype(np.float64)
                    speaking = True
            frame = np.clip(mic, -32768, 32767).astype(np.int16)
            residual = ec.residual_rms(frame)
            if not speaking:
                ec.accept()
            res_hist.append(residual)
            ref_hist.append(ec.last_ref_rms)
            del res_hist[:-W], ref_hist[:-W]
            ref = sum(ref_hist) / len(ref_hist)
            if ref > 1.0 and (user is None or speaking):
                out.append(sum(res_hist) / len(res_hist) / ref)
        return out

    def test_passes_audio_through_when_nothing_is_playing(self):
        """With no reference, every sound in the room is by definition not echo."""
        ec = EchoCanceller(frame=FRAME)
        frame = (np.random.default_rng(0).normal(0, 2000, FRAME)).astype(np.int16)
        self.assertAlmostEqual(ec.residual_rms(frame), frame_rms(frame), delta=1.0)
        self.assertFalse(ec.armed)

    def test_reset_forgets_the_room(self):
        ec = EchoCanceller(frame=FRAME)
        ec.reference(self.nova24[:8192].tobytes(), self.rate)
        self.assertTrue(ec.armed)
        ec.reset()
        self.assertFalse(ec.armed)

    def test_cost_stays_well_inside_the_frame_budget(self):
        """Runs in the mic callback, so it cannot be allowed to get expensive."""
        import time
        ec = EchoCanceller(frame=FRAME)
        rng = np.random.default_rng(0)
        for i in range(8):
            ec.reference(self.nova24[i * 4096:(i + 1) * 4096].tobytes(), self.rate)
        frames = [(rng.normal(0, 500, FRAME)).astype(np.int16) for _ in range(60)]
        t0 = time.perf_counter()
        for f in frames:
            ec.residual_rms(f)
        per_frame_ms = (time.perf_counter() - t0) / len(frames) * 1000
        self.assertLess(per_frame_ms, 8.0,
                        f"{per_frame_ms:.2f} ms per 64 ms frame is too slow")


class MuteTests(unittest.TestCase):
    def test_user_mute_sends_silence_and_never_barges_in(self):
        fired = []
        gate = VoiceGate(chunk_samples=FRAME, simple=False, on_barge_in=lambda: fired.append(1))
        gate.set_muted(True)
        gate.set_speaking(True)
        loud = (np.random.default_rng(0).normal(0, 9000, FRAME)).astype(np.int16)
        for _ in range(50):
            self.assertEqual(gate.process(loud), bytes(FRAME * 2))
        self.assertEqual(fired, [])

    def test_cooldown_suppresses_the_speaker_tail(self):
        gate = VoiceGate(chunk_samples=FRAME, simple=False)
        gate.set_speaking(True)
        gate.set_speaking(False)                      # natural finish
        tail = (np.random.default_rng(0).normal(0, 2000, FRAME)).astype(np.int16)
        self.assertEqual(gate.process(tail), bytes(FRAME * 2))


if __name__ == "__main__":
    unittest.main(verbosity=2)


class LockStalenessTests(unittest.TestCase):
    """A lock has to keep being true, not merely have been true once.

    `converged` gates the whole detector: claiming an echo path drops the
    evidence a barge-in needs from sixteen frames to two, and switches the
    test to a leak ratio that only means anything if the cancellation is
    real. So a lock that has stopped tracking is worse than no lock at all —
    it is the conservative policy switched off for nothing.

    Observed in a live conversation on a machine whose microphone driver does
    its own echo suppression, leaving nothing coherent to align to: the
    canceller caught one spurious correlation early on, then reported an echo
    path for the rest of the session at correlations of 0.10-0.14 with a
    residual *larger* than the reference. Three of five interruptions in that
    conversation were NOVA stopping for her own voice.
    """

    @classmethod
    def setUpClass(cls):
        nova, rate = _read(NOVA_WAV)
        cls.nova24, cls.rate = nova, rate
        cls.nova16 = _to_16k(nova, rate)

    def _play(self, ec, room, frames, start=0, seed=11):
        """Play NOVA through `room` (or through nowhere) for `frames` frames.

        The fixture is a few seconds long and these tests need more speech
        than that, so it repeats. NOVA talking for longer than one recording
        is the ordinary case, not a contrivance.
        """
        rng = np.random.default_rng(seed)
        avail = len(self.nova16) // FRAME - 1
        for n in range(start, start + frames):
            i = n % avail
            lo = i * FRAME * self.rate // 16000
            hi = (i + 1) * FRAME * self.rate // 16000
            ec.reference(self.nova24[lo:hi].tobytes(), self.rate)
            mic = rng.normal(0, 40, FRAME)
            if room is not None:
                mic += room.echo_of(self.nova16, (i + 1) * FRAME, FRAME)
            frame = np.clip(mic, -32768, 32767).astype(np.int16)
            ec.residual_rms(frame)
            ec.accept()
        return ec

    def test_a_real_echo_path_keeps_its_lock(self):
        """The case that must not regress: a coupled room stays coupled."""
        ec = self._play(EchoCanceller(frame=FRAME), Room(0.25), 200)
        self.assertTrue(ec.converged,
                        "a genuinely echoing room lost its lock, so NOVA now "
                        "needs a full second of speech to be interrupted")

    def test_a_path_that_stops_explaining_the_microphone_is_given_up(self):
        """The observed failure, reproduced: lock on a real echo, then take
        the echo away and keep playing.

        That is what a driver enabling its own echo suppression mid-session
        looks like from here, and what this machine looks like from the
        start — audible playback, nothing coherent coming back. The lock has
        to be surrendered, or barge-in stays on the two-frame fast path and
        NOVA stops for her own voice.
        """
        ec = self._play(EchoCanceller(frame=FRAME), Room(0.25), 60)
        self.assertTrue(ec.converged, "never locked, so the test proves nothing")

        self._play(ec, None, EchoCanceller.LOCK_STALE_FRAMES + 40, start=60)
        self.assertFalse(ec.converged,
                         "still claiming an echo path after the echo stopped")

    def test_a_lock_is_not_dropped_at_the_first_bad_frame(self):
        """Real rooms have frames the filter cannot explain. A handful of them
        is ordinary; only a sustained run means the path is gone."""
        ec = EchoCanceller(frame=FRAME)
        ec._locked_lag = 100          # pretend a lock was made
        ec._unconfirmed = 0
        ec._gain = 0.2
        for _ in range(EchoCanceller.LOCK_STALE_FRAMES - 1):
            ec._pending = (0.05, 0.2, 100, 1000.0, 990.0)   # nothing cancelled
            ec.accept()
        self.assertTrue(ec.converged, "gave up on the path far too readily")

    def test_a_good_frame_renews_the_lock(self):
        ec = EchoCanceller(frame=FRAME)
        ec._locked_lag, ec._gain = 100, 0.2
        for _ in range(EchoCanceller.LOCK_STALE_FRAMES - 1):
            ec._pending = (0.05, 0.2, 100, 1000.0, 990.0)   # nothing cancelled
            ec.accept()
        ec._pending = (0.9, 0.2, 100, 1000.0, 200.0)   # one clean echo frame
        ec.accept()
        self.assertEqual(ec._unconfirmed, 0)
        for _ in range(EchoCanceller.LOCK_STALE_FRAMES - 1):
            ec._pending = (0.05, 0.2, 100, 1000.0, 990.0)   # nothing cancelled
            ec.accept()
        self.assertTrue(ec.converged, "the renewal did not reset the count")

    def test_silence_never_costs_a_lock(self):
        """A silent reference says nothing about the echo path. Counting the
        pauses in NOVA's own speech against it would unlock her mid-sentence."""
        ec = EchoCanceller(frame=FRAME)
        ec._locked_lag, ec._gain, ec._unconfirmed = 100, 0.2, 0
        for _ in range(EchoCanceller.LOCK_STALE_FRAMES * 4):
            ec._pending = None            # nothing was playing: accept() no-ops
            ec.accept()
        self.assertTrue(ec.converged)

    def test_a_reset_forgets_the_staleness_too(self):
        """Sessions must start with no opinion about the room, in either
        direction."""
        ec = EchoCanceller(frame=FRAME)
        ec._locked_lag, ec._gain, ec._unconfirmed = 100, 0.2, 999
        ec.reset()
        self.assertEqual(ec._unconfirmed, 0)
        self.assertFalse(ec.converged)

    def test_a_run_of_middling_correlations_does_not_keep_a_path_alive(self):
        """The failure this threshold exists for.

        The search runs over roughly 9600 offsets, and the best of that many
        correlations of a signal as self-similar as speech clears 0.30 by
        chance regularly. So a machine with no echo path at all was having its
        lock renewed by spurious matches faster than staleness could retire
        it: every interruption in a long-talk session was granted an echo
        path, at correlations of -0.22, 0.17, -0.21 and -0.13.

        Cancelling at that offset is still worth attempting. Claiming the path
        is real — which buys the two-frame barge-in and the leak-ratio test —
        is not.
        """
        ec = EchoCanceller(frame=FRAME)
        ec._locked_lag, ec._gain, ec._unconfirmed = 100, 0.2, 0
        for corr in ([0.33, -0.31, 0.32, -0.34]
                     * (EchoCanceller.LOCK_STALE_FRAMES // 2)):
            ec._pending = (corr, 0.2, 100, 1000.0, 900.0)
            ec.accept()
        self.assertFalse(ec.converged,
                         "a lock kept alive by coincidence still grants the "
                         "two-frame fast path")

    def test_clean_echo_confirms_the_path(self):
        """The other side of the same threshold: real echo must still qualify,
        or NOVA needs a full second of speech to be interrupted on a machine
        where cancellation works perfectly well."""
        ec = EchoCanceller(frame=FRAME)
        ec._locked_lag, ec._gain, ec._unconfirmed = 100, 0.2, 0
        for _ in range(EchoCanceller.LOCK_STALE_FRAMES * 3):
            ec._pending = (0.83, 0.2, 100, 1000.0, 300.0)   # the measured median for echo
            ec.accept()
        self.assertTrue(ec.converged)

    def test_a_filter_that_removes_nothing_is_not_an_echo_path(self):
        """Correlation alone could not settle this.

        Raising the confirmation bar to 0.55 cut the spurious locks down but
        did not end them: over hundreds of frames the best of ~9600 offsets
        clears any fixed correlation sometimes, and one lucky frame renewed
        the lock. So the confirming test is the property the downstream branch
        actually assumes — that cancelling works. Measured here, the filter's
        gain had decayed to 0.06 and the "cancelled" residual was no smaller
        than the microphone.
        """
        ec = EchoCanceller(frame=FRAME)
        ec._locked_lag, ec._gain, ec._unconfirmed = 100, 0.2, 0
        for _ in range(EchoCanceller.LOCK_STALE_FRAMES + 4):
            # Beautifully correlated, and subtracting it achieves nothing.
            ec._pending = (0.95, 0.2, 100, 1000.0, 1000.0)
            ec.accept()
        self.assertFalse(ec.converged,
                         "claiming an echo path the filter cannot cancel")

    def test_cancellation_that_works_confirms_the_path(self):
        ec = EchoCanceller(frame=FRAME)
        ec._locked_lag, ec._gain, ec._unconfirmed = 100, 0.2, 0
        for _ in range(EchoCanceller.LOCK_STALE_FRAMES * 3):
            ec._pending = (0.83, 0.2, 100, 1000.0, 400.0)   # 8 dB removed
            ec.accept()
        self.assertTrue(ec.converged)
